  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  piston_position_controller:
    type: effort_controllers/JointVelocityController
    joint: PISTON
    pid: {p: 100.0, i: 0.1 , d: 0.0}
    
  F_Grip_position_controller:
    type: effort_controllers/JointVelocityController
    joint: F_Grip
    pid: {p: 10.0, i: 0.1, d: 0.0}
